# ================= length of string =================
length:
	gcc astrlen.c astrlen_test.c main.c -o len

# ================= comparing strings =================
comparing:
	gcc astr_cmp.c astr_cat_test.c main.c -o cmp

# ================== comparing n strings =================
comparingn:
	gcc astrn_ncmp.c astr_ncmp_test.c main.c -o ncmp

# ================= concatenation =================
concat:
	gcc astr_cat.c astr_cat_test.c main.c -o cat

# ================= n concatenation =================
nconcat:
	gcc astrncat.c astrncat_test.c main.c -o ncat

# ================= copy string =================
copy:
	gcc astr_cpy.c astrcpy_test.c main.c -o cpy

# ================= n copy string =================
ncpy:
	gcc astr_ncpy.c astr_ncpy_test.c main.c -o ncpy

# ================= clean =================
clean:
	rm -f *_s *_c 
