# ================= client-server interaction =================
client_server_interaction:
	gcc 02_server_engine.c 

# ================= iterative server =================
iterative:
	gcc IterativeServer-ultipleClients_S.c -o s
	gcc IterativeServer–MultipleClients_C.c -o c

# ================= just =================
just:
	gcc just_s.c -o s
	gcc just_c.c -o c