plain:
	gcc Plain_text_req_c.c -o c 
	gcc Plain_text_res_s.c -o s

structured:
	gcc Structured_req_c.c -o c 
	gcc Structured_res_s.c -o s

opcode:
	gcc Opcode_req_c.c -o c 
	gcc Opcode_res_s.c -o s

binary:
	gcc Binary_packet_req_c.c -o c 
	gcc Binary_packet_res_s.c -o s

clean:
	rm -f c s
